-- Create tax jurisdiction configuration tables
-- These tables store the platform-wide tax jurisdiction configuration
-- CEO-controlled with full audit trail

-- Tax Jurisdiction Configuration Table
CREATE TABLE IF NOT EXISTS tax_jurisdiction_config (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  jurisdiction TEXT NOT NULL CHECK (jurisdiction IN ('BR', 'EE')),
  country_name TEXT NOT NULL,
  country_code TEXT NOT NULL,
  flag TEXT NOT NULL,
  currency TEXT NOT NULL,
  currency_symbol TEXT NOT NULL,
  locale TEXT NOT NULL,
  tax_system JSONB NOT NULL,
  status TEXT DEFAULT 'active' NOT NULL CHECK (status IN ('active', 'inactive', 'migrating')),
  is_active BOOLEAN DEFAULT true NOT NULL,
  configured_at TIMESTAMP DEFAULT NOW() NOT NULL,
  configured_by UUID NOT NULL,
  configured_by_role TEXT NOT NULL,
  previous_jurisdiction TEXT CHECK (previous_jurisdiction IN ('BR', 'EE')),
  migrated_from TIMESTAMP,
  migration_reason TEXT,
  notes TEXT,
  migration_notes TEXT,
  created_at TIMESTAMP DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Index for quick active jurisdiction lookup
CREATE INDEX IF NOT EXISTS idx_tax_jurisdiction_config_active ON tax_jurisdiction_config(is_active, configured_at DESC) WHERE is_active = true;

-- Tax Jurisdiction History Table (Audit Trail)
CREATE TABLE IF NOT EXISTS tax_jurisdiction_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  config_id UUID NOT NULL REFERENCES tax_jurisdiction_config(id),
  action TEXT NOT NULL,
  from_jurisdiction TEXT CHECK (from_jurisdiction IN ('BR', 'EE')),
  to_jurisdiction TEXT NOT NULL CHECK (to_jurisdiction IN ('BR', 'EE')),
  changed_by UUID NOT NULL,
  changed_by_role TEXT NOT NULL,
  change_reason TEXT,
  change_notes TEXT,
  affected_records JSONB,
  migration_started TIMESTAMP,
  migration_completed TIMESTAMP,
  migration_status TEXT CHECK (migration_status IN ('pending', 'in_progress', 'completed', 'failed')),
  migration_errors JSONB,
  requires_approval BOOLEAN DEFAULT true,
  approved_by UUID,
  approved_at TIMESTAMP,
  approval_notes TEXT,
  changed_at TIMESTAMP DEFAULT NOW() NOT NULL,
  created_at TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Index for history queries
CREATE INDEX IF NOT EXISTS idx_tax_jurisdiction_history_config ON tax_jurisdiction_history(config_id, changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_tax_jurisdiction_history_changed_at ON tax_jurisdiction_history(changed_at DESC);

-- Tax Reports Table (Automated fiscal reports)
CREATE TABLE IF NOT EXISTS tax_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  report_type TEXT NOT NULL CHECK (report_type IN ('monthly', 'quarterly', 'annual', 'custom')),
  report_name TEXT NOT NULL,
  jurisdiction TEXT NOT NULL CHECK (jurisdiction IN ('BR', 'EE')),
  fiscal_year TEXT NOT NULL,
  fiscal_period TEXT NOT NULL,
  period_start_date TIMESTAMP NOT NULL,
  period_end_date TIMESTAMP NOT NULL,
  report_data JSONB NOT NULL,
  generated_files JSONB,
  status TEXT DEFAULT 'draft' NOT NULL CHECK (status IN ('draft', 'ready', 'filed', 'archived')),
  generated_at TIMESTAMP DEFAULT NOW() NOT NULL,
  generated_by UUID NOT NULL,
  generation_method TEXT NOT NULL CHECK (generation_method IN ('automatic', 'manual', 'scheduled')),
  filed_at TIMESTAMP,
  filed_by UUID,
  filing_reference TEXT,
  filing_receipt TEXT,
  notes TEXT,
  created_at TIMESTAMP DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Indexes for report queries
CREATE INDEX IF NOT EXISTS idx_tax_reports_tenant ON tax_reports(tenant_id, fiscal_period DESC);
CREATE INDEX IF NOT EXISTS idx_tax_reports_jurisdiction ON tax_reports(jurisdiction, fiscal_period DESC);
CREATE INDEX IF NOT EXISTS idx_tax_reports_status ON tax_reports(status, generated_at DESC);

-- Comments
COMMENT ON TABLE tax_jurisdiction_config IS 'Platform-wide tax jurisdiction configuration (CEO-controlled)';
COMMENT ON TABLE tax_jurisdiction_history IS 'Audit trail of all jurisdiction configuration changes';
COMMENT ON TABLE tax_reports IS 'Automated fiscal reports generated by the system';

COMMENT ON COLUMN tax_jurisdiction_config.jurisdiction IS 'Tax jurisdiction code: BR (Brazil) or EE (Estonia)';
COMMENT ON COLUMN tax_jurisdiction_config.tax_system IS 'Complete tax system configuration including VAT rates, corporate tax, etc.';
COMMENT ON COLUMN tax_jurisdiction_config.is_active IS 'Only one configuration can be active at a time';

-- Insert initial data (optional - can be done via API)
-- Example: Configure for Brazil
-- INSERT INTO tax_jurisdiction_config (jurisdiction, country_name, country_code, flag, currency, currency_symbol, locale, tax_system, configured_by, configured_by_role)
-- VALUES ('BR', 'Brazil', 'BRA', '🇧🇷', 'BRL', 'R$', 'pt-BR', '{"vatRates": {"standard": 18}, "corporateTaxRates": {"standard": 24}, "personalIncomeTax": {"type": "progressive"}, "specialFeatures": ["NF-e", "SPED"], "complianceRequirements": ["NF-e", "SPED"]}', 'system', 'SYSTEM');

-- Success message
SELECT 'Tax jurisdiction tables created successfully!' AS message;
